export const CREATE_USER_WITH_EMAIL_AND_PASSWORD = 'CREATE_USER_WITH_EMAIL_AND_PASSWORD'
export const SIGNIN_USER_WITH_EMAIL_AND_PASSWORD = 'SIGNIN_USER_WITH_EMAIL_AND_PASSWORD'
export const DO_SIGNOUT = 'DO_SIGNOUT'
export const DO_PASSWORD_RESET = 'DO_PASSWORD_RESET'
export const DO_PASSWORD_CHANGE = 'DO_PASSWORD_CHANGE'

